### ISSUE TITLE
There is a possibility of an uninstall not being able to complete fully due to a mesos master failover event.

### ISSUE THREAD

**Issue by BenWhitehead** [dcos/cosmos#183]
Due to [Mesos not redirecting to the leader](https://issues.apache.org/jira/browse/MESOS-1865) there is a possiblity an uninstall won't complete.

###### Scenario
Mesos multi-master setup (3 nodes, 1 leader)

User wants to uninstall `serviceA` which also has a framework `frameworkA`.

Based on the current behavior, the marathon app running the scheduler for `serviceA` will be removed, but the call to mesos to teardown `frameworkA` can fail due to mesos not redirecting to the leading master (or even if the master isn't available).

**Comment by neilconway** [comment]
FYI, the Mesos bug has been fixed and will ship in 0.29
