### ISSUE TITLE
Stub universe causes dcos-cli to return uninformative errors

### ISSUE THREAD

**Issue by nickbp** [dcos/cosmos#281]
Upon installing a custom 'stub' universe package, Cosmos returns errors when running commands that would involve reading from that package. I expect the root cause is a formatting issue in the package itself (see url below), but Cosmos isn't being helpful in diagnosing the problem, only printing out a path to a file and returning an error code.

Versions:

dcos-cli: master c60b454bf2900ad19c84bdacc8a2b2f535d158d9
cosmos: Whatever's in continuous/testing as of this morning. Keeping up ccm instance "nick-z8jhi4y" for this bug

Steps from dcos cli:

$ dcos package repo add --index=0 kafka https://s3-us-west-2.amazonaws.com/infinity-artifacts/autodelete7d/kafka/20160302-012140-G9JV6iKX2a8i29kt/stub-universe-kafka.zip
$ dcos package install kafka
/var/lib/cosmos/repository654277774004654795/scripts/.stub_dir
$ echo $?
1
$ dcos package describe kafka
/var/lib/cosmos/repository1487061576548986144/scripts/.stub_dir
$ echo $?
1

**Comment by BenWhitehead** [comment]
This error should be avoided with the updates to repo fetching made this release. When fetching a zip files if the response is not 200 and error will be returned indicating as such.

I'm going to close this unless @cruhland Can you confirm that missing directory entries is still an issue.
