### ISSUE TITLE
Investigate which repo Zip file layouts should be supported

### ISSUE THREAD

**Issue by cruhland** [dcos/cosmos#282]
Currently our Zip file extraction code for repo bundles assumes that directory entries will occur before the entries for the files they contain. This logic fails for some Zip files created by users. Should we perform more validation on the Zip file structure and report violations to users? Or should we be more flexible in our extraction logic?

Definition of done: decide which approach to take, and implement it.

**Comment by cruhland** [comment]
Making a partial decision on this: we will support Zip files that do not contain directory entries. The directories can be inferred from the file entry paths, and created with [`Files.createDirectories`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createDirectories-java.nio.file.Path-java.nio.file.attribute.FileAttribute...-).

**Comment by BenWhitehead** [comment]
Since we're moving away from zip files what we've settled on today is:

1. Zip files can contain only files (directory entries are not required)
2. All zip files must be in universe version-2.x layout and be nested under a single top level directory (with any name)
