### ISSUE TITLE
Attempting to use a repo that doesn't contain a top level directory in the zip fails with an error

### ISSUE THREAD

**Issue by BenWhitehead** [dcos/cosmos#290]
```
{
    "data": null,
    "message": "Index file missing for repo [...repo_uri...]",
    "type": "IndexNotFound"
}
```

We should investigate what it would take to be tolerant of a zip not containing a top level directory.

**Comment by jsancio** [comment]
@BenWhitehead I say we close this. We are moving away from zip file to JSON documents.

**Comment by BenWhitehead** [comment]
I think it's probably okay to close.
