### ISSUE TITLE
Include file names in error response from package file validation

### ISSUE THREAD

**Issue by cruhland** [dcos/cosmos#305]
We had a customer issue today that was difficult to diagnose because the error response received from Cosmos was the following:

```json
{
  "data": null,
  "message": "OneAnd(com.mesosphere.cosmos.PackageFileSchemaMismatch,List())",
  "type": "NelErrors"
}
```

Which comes from [`UniversePackageCache.readPackageFiles`](https://github.com/mesosphere/cosmos/blob/ba7e0b894586b061c70e2d5c07c0a974a5dc346c/cosmos-server/src/main/scala/com/mesosphere/cosmos/UniversePackageCache.scala#L396). The customer was using a modified Universe repo and it turned out that they had dropped the required `packagingVersion` field from the `package.json` of Chronos.

**Deliverable**: the error response generation for the `NelErrors` type should be made more robust, so that the details of all errors it contains are included in the response. We should also avoid serializing the data structure directly in the `message` field, and instead put the details in `data` where they can be parsed.

**Comment by cruhland** [comment]
Additional requirement from #341 -- each nested error in the array under `data` should be rendered in exactly the same way as it would appear in a response body by itself.

**Comment by jsancio** [comment]
@cruhland I think we can close this issue, no?

**Comment by cruhland** [comment]
@jsancio yes, this is specifically about improving how `NelErrors` is rendered in responses. It turns out that `NelErrors` is no longer used after we got rid of `UniversePackageCache`, so I've created a separate issue to delete it (#426). I'll close this one.
