### ISSUE TITLE
Only a subset of PackageDefinition should be in a Marathon label

### ISSUE THREAD

**Issue by cruhland** [dcos/cosmos#397]
From a comment by @BenWhitehead on PR #391 in reference to [this line](https://github.com/dcos/cosmos/pull/391/files#diff-f322663c002480f19948ce88c7435b10R248):

> I don't think we want to do this. having json documents in json strings is a bad thing. I also don't think we want to encode the entire package into this label. between the config.json and marathon template this can easily get to very large sizes. If these documents are large it will place a lot of stress on marathon due to the zk 1mb node size limit.

**Comment by jsancio** [comment]
Fixed by #413
