### ISSUE TITLE
Investigate the render endpoint with latest changes.

### ISSUE THREAD

**Issue by jsancio** [dcos/cosmos#417]
- [x] Test that the render endpoint works with version 2 universe which requires a Marathon template
- [ ] ~~Test that the render endpoint works with version 3 universe without a Marathon template.~~

**Comment by jsancio** [comment]
@tamarrow I created an issues for this. We may be able to test it manually for now. To test it as part of our integration test we can wait until #317.

**Comment by BenWhitehead** [comment]
Render will error with an appropriate message if a user attempts to render a v3 package that does not have a marathon template. If a v3 package has a template, render will return normally.
