### ISSUE TITLE
Improve error message when filled-in Marathon template is parsed

### ISSUE THREAD

**Issue by cruhland** [dcos/cosmos#437]
Here's an example of the current message:

```
Package file [marathon.json] is not JSON: expected : got a (line 20, column 488)
```

This could be reworded to give more help to the user, for example:

```
Unable to parse filled-in Marathon template as JSON; there may be an error in the package's Marathon template or default configuration options, or in the installation request's options. Parsing error was: expected : got a (line 20, column 488)
```

The error is generated [here](https://github.com/dcos/cosmos/blob/b9cdef24eaf0b444b28f45142be7e7e973faf416/cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageInstallHandler.scala#L131).

**Comment by larioj** [comment]
How do I reproduce the error?

**Comment by cruhland** [comment]
One way would be to have a Universe package with a `marathon.json.mustache` file that contains a malformed JSON document. When the mustache template is filled in, Cosmos attempts to parse the resulting file as JSON, which produces this error.
