### ISSUE TITLE
switch HttpURLConnection to finagle

### ISSUE THREAD

**Issue by aeyakovenko** [dcos/cosmos#455]
Switch HttpURLConnection to finagle in UniverseClient.scala .  [Finagle] doesn't support `http.nonProxyHosts`.  Test if the url is in the `http.nonProxyHosts` via the [ProxySelector].   Call `ProxySelector.getDefault().select(URI.create(testUrl));` and check if the returned proxy is a NO_PROXY.

[Finagle]: https://twitter.github.io/finagle/guide/Clients.html#http-proxy
[ProxySelector]: https://docs.oracle.com/javase/7/docs/api/java/net/ProxySelector.html

**Comment by jsancio** [comment]
Migrated.
