### ISSUE TITLE
Provide mechanism to create an S3-compatible store and attach it to Cosmos

### ISSUE THREAD

**Issue by cruhland** [dcos/cosmos#466]
~~Preferred option: see if the CloudFormation templates and/or CCM can be modified to~~

1. ~~create the bucket on cluster creation;~~
1. ~~make the bucket URI available on the Cosmos command line when it starts;~~
1. ~~delete the bucket on cluster deletion.~~

~~Ask @lingmann for details.~~

Met with @lingmann, @pyronicide, and others about the above proposal. The conclusion was that although direct support in the CloudFormation templates would be nice, it's something to consider adding later once the S3 storage has been confirmed to work and customers would appreciate the convenience of not having to set it up themselves.

For now, we should provide scripts that customers can use to attach and detach S3 storage to and from Cosmos. Things to consider:
- Should the scripts create/destroy the bucket, or leave that up to the customer?
- How should the bucket information be communicated to Cosmos?
    - Endpoint(s)
    - Shutdown Cosmos, restart with different environment variables or command-line flags
    - Modify data in ZooKeeper
    - etc.

We can test these scripts by using them to provide S3 storage for our integration tests, which we will need in any case.

**Comment by cruhland** [comment]
I've added two build steps to the integration tests CI for Cosmos: https://teamcity.mesosphere.io/admin/editBuildRunners.html?id=buildType:DcosIo_Cosmos_FullClusterIntegrationTests

And tested that they work: https://teamcity.mesosphere.io/viewLog.html?buildId=368410&buildTypeId=DcosIo_Cosmos_FullClusterIntegrationTests&tab=buildLog

**Comment by jsancio** [comment]
I think that we should use ZooKeeper to learn what values to use. I know that @cmaloney has express concerns when having to configure N number of process with similar values for them to work. How do you determine the right set of command line flags and environment variables, and replicate that configuration to the N process.

We should also consider using the secret store for discovering authentication information for S3. @alberts, what's the plan for exposing the a secrets API across all versions of DC/OS?

**Comment by cmaloney** [comment]
This is fairly different from the "really simple caching" that we need in the short term. That is just a basic either reverse-proxy cache which always saves (I have a simple python script I can hand that does that).

**Comment by cruhland** [comment]
Agreed, @cmaloney. Could you create another issue with your short-term requirements? Thanks!

**Comment by cmaloney** [comment]
Created: https://github.com/dcos/cosmos/issues/476

**Comment by jsancio** [comment]
Migrated.
