### ISSUE TITLE
Define an `S3Client` trait with only the operations needed by Cosmos

### ISSUE THREAD

**Issue by cruhland** [dcos/cosmos#467]
The trait will be used by the `PackageStorage` class, and allows us to use different implementations of the S3 operations to assist with testing. There should be a method on the trait for each operation:

- [PUT Object](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html),
- [GET Object](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html), and
- [GET Bucket](http://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html),

but note that not all of their features should be implemented -- just the subset required by the `PackageStorage` class.

---
At least one class implementing `S3Client` should be written using an actual S3 client library. In order to ensure the class will be useful for integration testing, a service implementing the S3 HTTP API needs to be accessible to the `CosmosIntegrationTestServer`. Determine how to accomplish this when the tests are run both on local developer machines and in CI jobs, and prove that the approach works by writing an integration test exercising the implementation of `S3Client`.

**Comment by jsancio** [comment]
Duplicated by #480
