### ISSUE TITLE
Define trait that `PackageStorage` will use for ZooKeeper operations 

### ISSUE THREAD

**Issue by cruhland** [dcos/cosmos#469]
The `PackageStorage` class needs to use ZooKeeper to generate unique `releaseVersion` field values for uploaded packages, at a minimum. To prevent `PackageStorage` from depending on the entire Curator library, define a trait with only the necessary operations.

When implementing the trait, use the `ZooKeeperStorage` class that has already been defined. It will need to be refactored a bit -- all of the operations specific to the repository list should be factored out into another class.

**Comment by jsancio** [comment]
This has been fixed.
