### ISSUE TITLE
Implement package upload endpoint

### ISSUE THREAD

**Issue by cruhland** [dcos/cosmos#471]
- The request body will be a Universe v3 `V3Package` JSON object, sans `releaseVersion` field.
- The endpoint should parse and validate the body as a `PackageBundle` object
- The endpoint should write the bundle to package storage using a trait or traits passed in to the constructor of the endpoint handler class, as follows:
    1. Get and increment `releaseVersion` counter value from ZooKeeper
    1. Convert the bundle into a `PackageDefinition` by adding the `releaseVersion`
    1. Create object key for S3: `s"$packageName/$releaseVersion"`
    1. Perform "PUT Object" operation on S3 API

**Comment by jsancio** [comment]
Migrated.
