### ISSUE TITLE
Implement (temporary) "repo view" endpoint

### ISSUE THREAD

**Issue by cruhland** [dcos/cosmos#472]
This endpoint implements the [same protocol](https://github.com/mesosphere/universe#consumption-protocol) as the Universe server, because it is intended to be used in Cosmos's repository list. The packages returned by this endpoint are the ones that have been uploaded into package storage.

Using a trait or traits passed into the endpoint handler constructor, the code should roughly do the following:

1. Repeatedly invoke "GET Bucket" on S3 API, to accumulate all pages of object (package) keys
1. Invoke "GET Object" on each object key, to get the Universe v3 JSON for each package
1. Wrap list of packages in a repository JSON and send in response

**Comment by jsancio** [comment]
We agree we don't need this anymore.
