### ISSUE TITLE
Reduce package bandwidth usage

### ISSUE THREAD

**Issue by cmaloney** [dcos/cosmos#476]
Currently every time someone "installs" something from universe, a marathon app is created, and that marathon app has all the URIs which were specified in the marathon.json in the universe.

Sometimes , those marathon apps fail to launch (for whatever reason), meaning the task tries to get to deployed to a new host. This repeats forever.

Sometimes, the app is short lived, or launches a bunch of instances on a cluster (thousands).

Currently there are a whole bunch of these artifacts which are being downloaded very rapidly compared to how frequently the package is actually being installed / downloaded.

Making it so cosmos had a very simple caching reverse proxy (Assume artifacts don't change, don't try co-ordinating between nodes / downloading once per master is fine, etc) would save us quite a bit of bill, and customers a lot of external bandwidth they likely don't realize they're even using (TB of bandwidth)

**Comment by jsancio** [comment]
Migrated.
