### ISSUE TITLE
LocalRepositoryHash for distributed publish

### ISSUE THREAD

**Issue by larioj** [dcos/cosmos#506]
I need to discuss the actual implementation of this since there seems to be some issues surrounding the storage of this element. See #478 for high level view of why this change is required.

**Comment by larioj** [comment]
PR relating to this issue #495

**Comment by larioj** [comment]
Etags must have the following format:

     ETag       = entity-tag
     entity-tag = [ weak ] opaque-tag
     weak       = %x57.2F ; "W/", case-sensitive
     opaque-tag = DQUOTE *etagc DQUOTE
     etagc      = %x21 / %x23-7E / obs-text
                ; VCHAR except double quotes, plus obs-text

This means that they can be arbitrarily long

**Comment by larioj** [comment]
@jsancio and I had a discussion on how to address @BenWhitehead comments on #495 about not storing an ETag independently. The argument being that an ETag makes no sense on it's own, thus it must not be stored independently. We agreed with point, and decided that ETag is not the right descriptor for this element. This model element is now called LocalRepositoryHash, since this makes more sense for our use case. We are using the LocalRepositoryHash to determine if the contents of the local repository have changed.

**Comment by jsancio** [comment]
migrated.
