### ISSUE TITLE
Install actor for Local packages

### ISSUE THREAD

**Issue by tamarrow** [dcos/cosmos#510]
1. Accept package.dcos (blocking)
2. Check disk space
3. Store package.dcos in s3 (potentially blocking)
4. Add to zk backed Install Queue
5. Package Coordinate -> s3 url of package.dcos
6. Extract package manifest 
  - Package.dcos likely a zip file
7. Upload package.json (manifest) to S3
8. Delete znode (package is now installed)

**Comment by tamarrow** [comment]
partial interface: #507

**Comment by jsancio** [comment]
Migrated.
